[metadata]
name = "sesh"
description = "Tmux session picker via sesh"
requirements = ["sesh"]

[source]
command = [
  "sesh list --icons",
  "sesh list -t --icons",
  "sesh list -c --icons",
  "sesh list -z --icons",
  "fd -H -d 2 -t d -E .Trash . ~",
]

[preview]
command = "echo {}"

[actions.connect]
description = "Connect to session"
command = "sesh connect '{strip_ansi|split: :1..|join: }'"
mode = "execute"

[actions.kill_session]
description = "Kill tmux session"
command = "tmux kill-session -t '{strip_ansi|split: :1..|join: }'"
