# modules/home-manager/shell/starship.toml

# Main prompt format
format = """
$time\
$docker_context\
$kubernetes\
$aws\
$gcloud\
$azure\
$line_break\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$nix_shell\
$cmd_duration\
$line_break\
$character\
"""

[username]
style_user = "white"
format = "[$user]($style_user)"
show_always = true

[hostname]
format = "[([@](#40a02b)[$hostname](white)) @osIcon@](#40a02b) "
ssh_only = false
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# --- All your other module settings ---
[time]
disabled = false
format = "[$time]($style)"
time_format = "[ %H:%M:%S] "
utc_time_offset = "local"
style = "dimmed"

[docker_context]
symbol = " "
format = "[\\[$symbol($context)\\]](cyan) "
only_with_files = false
disabled = false
style = "dimmed"

[kubernetes]
symbol = "⎈ "
format = "[\\[$symbol$context(::$namespace)\\]](blue) "
disabled = false
style = "dimmed"

[aws]
symbol = " "
format = "[\\[$symbol$profile(::$region)\\]](yellow) "
disabled = false

[gcloud]
symbol = " "
format = "[\\[$symbol$active(::$region)\\]](bold blue) "
disabled = false

[azure]
symbol = " "
format = "[\\[$symbol$subscription\\]](bold cyan) "
disabled = false

[buf]
symbol = " "
[c]
symbol = " "
[dart]
symbol = " "
[directory]
read_only = " "
[elixir]
symbol = " "
[elm]
symbol = " "
[git_branch]
symbol = " "
[golang]
symbol = " "
[haskell]
symbol = " "
[hg_branch]
symbol = " "
[java]
symbol = " "
[julia]
symbol = " "
[lua]
symbol = " "
[memory_usage]
symbol = "󰘚 "
[nim]
symbol = " "
[nix_shell]
symbol = " "
[nodejs]
symbol = " "
[package]
symbol = "󰏗 "
[python]
symbol = " "
[rlang]
symbol = " "
[ruby]
symbol = " "
[rust]
symbol = " "
[scala]
symbol = " "
