# modules/home-manager/shell/starship.toml

# Main prompt format
format = """
$time\
$docker_context\
$kubernetes\
$aws\
$gcloud\
$azure\
$nix_shell\
$line_break\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

[username]
style_user = "yellow"
style_root = "red"
format = "[$user]($style)"
show_always = true

[hostname]
format = "[@$hostname]($style) in "
ssh_only = false
disabled = false
style = "white dimmed"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# --- All your other module settings ---
[time]
disabled = false
format = "[@osIcon@](bold white) [$time]($style) "
time_format = "[ %H:%M:%S]"
utc_time_offset = "local"
style = "white dimmed"

[docker_context]
symbol = " "
format = "[\\[$symbol($context)\\]]($style) "
only_with_files = false
disabled = false
style = "cyan dimmed"

[kubernetes]
symbol = "⎈ "
format = "[\\[$symbol$context(::$namespace)\\]]($style) "
disabled = true
style = "blue dimmed"

[aws]
symbol = " "
format = "[\\[$symbol$profile(::$region)\\]]($style) "
disabled = false
style = "bold yello dimmed"

[gcloud]
symbol = " "
format = "[\\[$symbol$active(::$region)\\]]($style) "
disabled = false
style = "bold blue dimmed"

[azure]
symbol = " "
format = "[\\[$symbol$subscription\\]]($style) "
disabled = false
style = "bold cyan dimmed"

[nix_shell]
symbol = " "
format = "[\\[$symbol$state\\]]($style)"
style = "blue dimmed"

[buf]
symbol = " "
[c]
symbol = " "
[dart]
symbol = " "
[directory]
read_only = " "
[elixir]
symbol = " "
[elm]
symbol = " "
[git_branch]
symbol = " "
[golang]
symbol = " "
[haskell]
symbol = " "
[hg_branch]
symbol = " "
[java]
symbol = " "
[julia]
symbol = " "
[lua]
symbol = " "
[memory_usage]
symbol = "󰘚 "
[nim]
symbol = " "
[nodejs]
symbol = " "
[package]
symbol = "󰏗 "
[python]
symbol = " "
[rlang]
symbol = " "
[ruby]
symbol = " "
[rust]
symbol = " "
[scala]
symbol = " "
