min_log_level = info
file_apps = /home/@username@/.config/sunshine/apps.json

fps = [10, 30, 60, 75, 90, 120]
resolutions = [
    1280x720,
    1920x1080,
    2560x1440,
    3840x2160
]

encoder = nvenc
nvenc_preset = p5
nvenc_tune = ll
nvenc_rc = cbr
nvenc_bitrate_kbps = 60000
nvenc_coder = auto

audio_backend = pipewire
audio_sink = GameAudioSink

key_repeat_delay = 500
key_repeat_frequency = 24

channels = 2
port = 47989
origin_web_ui_allowed = pc
upnp = on

file_state = /home/@username@/.config/sunshine/sunshine_state.json
