# Sources
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/binds.conf
#source = ~/.config/hypr/gaming.conf

# Single 49" ultrawide
monitor=DP-1, 5120x1440, 0x0, 1

#exec-once = exec ~/.config/hypr/launch
#exec-once = exec ~/.config/waybar/launch.sh

# Load plugins from HYPR_PLUGIN_DIR (provided by Nix/flake)
exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"
exec-once = hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprscrolling.so"

#exec-once = dbus-update-activation-environment --systemd --all

exec-once = bash -c "wl-paste --watch cliphist store &"
exec-once = dms run
#exec-once = {{POLKIT_AGENT_PATH}}

debug:full_cm_proto = true

# NVIDIA Wayland env
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

env = QT_QPA_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = QT_QPA_PLATFORMTHEME,gtk3
env = QT_QPA_PLATFORMTHEME_QT6,gtk3

input {
  kb_layout = us,no
  kb_options = grp:alt_shift_toggle
  numlock_by_default = true

  follow_mouse = 2

  touchpad {
    natural_scroll = yes
  }

  sensitivity = 1.0
}

general {
  gaps_in = 2.5
  gaps_out = 2.5
  border_size = 1

  layout = scrolling
  allow_tearing = true
  no_focus_fallback = false
}

decoration {
  rounding = 5
  active_opacity = 1.0
  inactive_opacity = 0.95
  
  shadow {
      enabled = true
      range = 30
      render_power = 5
      offset = 0 5
      color = rgba(00000070)
  }
}

animations {
  enabled = false 
}

dwindle {
  pseudotile = false
  preserve_split = false
  use_active_for_splits = yes
}

# Master layout tuned for ultrawide (if you switch back)
master {
  mfact = 0.5
  orientation = left
  special_scale_factor = 0.9
}

# Gaming misc
misc {
  #force_default_wallpaper = 0
  disable_hyprland_logo = true
  #vrr = 2
}

plugin {
  hyprscrolling {
    column_width = 0.25
    fullscreen_on_one_column = false
    focus_fit_method = 1 
    follow_focus = true
    # Presets for SUPER+CTRL+comma
    #explicit_column_widths = 0.2,0.25,0.5,0.6
    explicit_column_widths = 0.167,0.25,0.333,0.5,1
  }
}
