# hyprland.conf

# Sources
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/managed-overrides.conf

# 1. MONITOR SETUP (iGPU via DP)
monitor=DP-1, preferred, 0x0, 1

# 2. DISABLE OTHER PORTS IN MAIN SESSION
# This ensures Hyprland doesn't try to touch the dummy plug
#monitor=HDMI-A-1, disable
monitor=HDMI-A-3, disable

# 3. FORCE iGPU FOR COMPOSITOR
# pci-0000:79:00.0 is your AMD iGPU
#env = WLR_DRM_DEVICES,/dev/dri/by-path/pci-0000:79:00.0-card
#env = LIBVA_DRIVER_NAME,radeonsi
#env = __GLX_VENDOR_LIBRARY_NAME,mesa
#env = GBM_BACKEND,drm--pure

# NVIDIA Wayland env
#env = LIBVA_DRIVER_NAME,nvidia
#env = XDG_SESSION_TYPE,wayland
#env = GBM_BACKEND,nvidia-drm
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia

env = QT_QPA_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = QT_QPA_PLATFORMTHEME,gtk3
env = QT_QPA_PLATFORMTHEME_QT6,gtk3

exec-once = bash -c "wl-paste --watch cliphist store &"
exec-once = dms run
exec-once = ~/.config/hypr/scripts/dms_resume_watcher.sh
exec-once = systemctl --user start --no-block hyprscratch.service

debug:full_cm_proto = true

input {
  kb_layout = us,no
  kb_options = grp:alt_shift_toggle
  numlock_by_default = true

  follow_mouse = 2

  touchpad {
    natural_scroll = yes
  }

  sensitivity = 1.0
}

general {
  gaps_in = 2
  gaps_out = 2
  border_size = 2

  layout = scrolling
  allow_tearing = true
  no_focus_fallback = false
}

decoration {
  rounding = 2

  active_opacity = 1.0
  inactive_opacity = 0.95
  
  shadow {
      enabled = true
      range = 30
      render_power = 5
      offset = 0 5
      color = rgba(00000070)
  }
}

animations {
  enabled = true 

  bezier = myBezier, 0.05, 0.9, 0.1, 1.0

  animation = windows, 1, 3, myBezier
  animation = windowsOut, 1, 3, default, popin 80%
  animation = border, 1, 5, default
  animation = fade, 1, 3, default
  animation = workspaces, 1, 4, default, slidevert
  animation = specialWorkspace, 0
}

dwindle {
  pseudotile = false
  preserve_split = false
  use_active_for_splits = yes
}

# Master layout tuned for ultrawide (if you switch back)
master {
  mfact = 0.5
  orientation = left
  special_scale_factor = 0.9
}

# Gaming misc
misc {
  #force_default_wallpaper = 0
  disable_hyprland_logo = true
  #vrr = 2
}

scrolling {
  column_width = 0.333
  fullscreen_on_one_column = false
  focus_fit_method = 1
  follow_focus = false
  # Presets for SUPER+comma/period
  explicit_column_widths = 0.166,0.25,0.333,0.5,0.666,1
}

source = ./dms/outputs.conf
source = ~/.config/hypr/host.conf
