-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

local config_home = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
local hypr_config_dir = os.getenv("HYPRLAND_CONFIG_DIR") or (config_home .. "/hypr")
package.path = hypr_config_dir .. "/?.lua;" .. hypr_config_dir .. "/?/init.lua;" .. package.path

hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")
-- Hyprland 0.56's focus-grab path can immediately clear DMS modal surfaces.
-- Let DMS use exclusive layer-shell keyboard focus for stable launchers.
hl.env("DMS_HYPRLAND_EXCLUSIVE_FOCUS", "1")

hl.on("hyprland.start", function()
	hl.exec_cmd("wl-paste --watch cliphist store &")
	hl.exec_cmd("dms run")
	hl.exec_cmd("~/.config/hypr/scripts/dms_resume_watcher.sh")
	hl.exec_cmd("systemctl --user start --no-block hyprscratch.service")
end)

hl.config({
	debug = {
		full_cm_proto = true,
	},
	input = {
		kb_layout = "us,no",
		kb_options = "grp:alt_shift_toggle",
		numlock_by_default = true,
		follow_mouse = 2,
		touchpad = {
			natural_scroll = true,
		},
		sensitivity = 1.0,
	},
	general = {
		gaps_in = 2,
		gaps_out = 2,
		border_size = 2,
		layout = "scrolling",
		allow_tearing = true,
		no_focus_fallback = false,
	},
	decoration = {
		rounding = 2,
		active_opacity = 1.0,
		inactive_opacity = 0.95,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	animations = {
		enabled = true,
	},
	dwindle = {
		preserve_split = false,
		use_active_for_splits = true,
	},
	master = {
		mfact = 0.5,
		orientation = "left",
		special_scale_factor = 0.9,
	},
	misc = {
		disable_hyprland_logo = true,
		-- Permit the lock wrapper to replace a crashed locker without clearing
		-- the compositor's secure lock state.
		allow_session_lock_restore = true,
	},
	scrolling = {
		column_width = 0.333,
		fullscreen_on_one_column = false,
		focus_fit_method = 1,
		follow_focus = false,
		explicit_column_widths = "0.25,0.333,0.5,0.666,1",
	},
})

hl.curve("myBezier", {
	type = "bezier",
	points = { { 0.05, 0.9 }, { 0.1, 1.0 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "default", style = "slidevert" })
hl.animation({ leaf = "specialWorkspace", enabled = false })

-- Baseline output policy. Host and DMS output modules load later and can
-- override these entries with more specific modes and positions.
hl.monitor({ output = "DP-1", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "HDMI-A-3", disabled = true })

-- Launcher workspaces are named but remain unpinned to outputs. Application
-- routing is host-specific and does not attach lifecycle behavior.
hl.workspace_rule({
	workspace = "7",
	default_name = "steam",
})
hl.workspace_rule({
	workspace = "8",
	default_name = "battle-net",
})

-- Workspace 10 is reserved for responsive frontend development.
-- Keep its tiled geometry exact so breakpoint-width columns are not reduced
-- by compositor gaps or borders.
hl.workspace_rule({
	workspace = "10",
	default_name = "frontend",
	gaps_in = 0,
	gaps_out = 0,
	border_size = 0,
})

local function reload_module(name)
	-- Hyprland keeps the Lua VM alive across configuration reloads. Clear the
	-- standard require cache so every declared module is reapplied after the
	-- compositor resets its configuration state.
	package.loaded[name] = nil
	require(name)
end

reload_module("colors")

-- Lua keybind objects survive a configuration reload. Remove the previous
-- registry before recreating it, otherwise every reload doubles each action.
hl.unbind("all")
package.loaded["binds-scrolling"] = nil
package.loaded["binds-dwindle"] = nil
reload_module("binds")
reload_module("managed-overrides")
reload_module("dms.outputs")
reload_module("dms.cursor")
reload_module("dms.windowrules")
reload_module("host")
