audio_sink = GameAudioSink.monitor
channels = 2
fps = 60
bitrate = 30000
min_log_level = info
port = 47989
upnp = on

[apps]

[[apps.Steam Big Picture (Gamescoped)]]
name = "Steam Big Picture (Gamescoped)"
prep-cmd = [
  { do = "prepare-streaming-audio", undo = "restore-default-audio" }
]
cmd = "gamescope-steam"

[[apps.EmulationStation-DE]]
name = "EmulationStation-DE (Gamescoped)"
prep-cmd = [
  { do = "prepare-streaming-audio", undo = "restore-default-audio" }
]
cmd = "gamescope -W 1920 -H 1080 -r 60 -f --expose-wayland -- emulationstation-de"

[[apps.Desktop]]
name = "Desktop"
prep-cmd = [
  { do = "prepare-streaming-audio", undo = "restore-default-audio" }
]
cmd = "hyprctl dispatch workspace 1"
